baseURL = 'https://quinnah.github.io/'
languageCode = 'en-us'
title = "Quinna's Website"
theme = "PaperMod"

[params]
  color = 'wheat'                 # linen, wheat, gray, light
  mainSections = ["home"]
  socialIcons = [
  { name = 'github', url = 'github.com/quinnah' },
  { name = 'email', url = 'quinnah@umich.edu' },
]
