baseURL = 'https://quinnah.github.io/'
languageCode = 'en-us'
title = "Quinna's Website"
theme = "PaperMod"

[params]
  color = 'wheat'     
  mainSections = ["singles"]            # linen, wheat, gray, light
  socialIcons = [
  { name = 'github', url = 'github.com/quinnah' },
  { name = 'email', url = 'quinnah@umich.edu' },
]

[permalinks]
  singles = "/:title/"